name: Owners Bot

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, labeled, unlabeled]

jobs:
  handle-comment:
    if: >-
      github.event_name == 'pull_request' ||
      (github.event_name == 'issue_comment' && github.event.issue.pull_request)
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Run Owners Bot
        uses: coreos/owners-file-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          owners-file: "OWNERS"
        env:
          AUTO_MERGE: true
          MERGE_STRATEGY: merge
